
import React, { createContext, useState, useContext } from 'react';
import { Language } from '../types';

const TRANSLATIONS = {
  [Language.EN]: {
    slogan: "Don't just vote. Live your values.",
    nav: { feed: "FEED", sense: "SENSE", stance: "STANCE", union: "UNION" },
    login: {
        title: "IDENTIFY YOURSELF",
        email: "EMAIL FREQUENCY",
        key: "ACCESS KEY",
        btn: "ESTABLISH LINK",
        google: "CONTINUE WITH GOOGLE",
        protocol: "Zero-Knowledge Protocol",
        sign_up_prompt: "Don't have an account? Sign Up",
        sign_in_prompt: "Already have an account? Sign In",
        encrypted_channel: "ENCRYPTED CHANNEL"
    },
    menu: {
        manifesto: "MANIFESTO",
        privacy: "PRIVACY",
        settings: "SETTINGS",
        account: "ACCOUNT",
        aboutUs: "ABOUT US",
        social: "SOCIAL MEDIA",
        logout: "LOGOUT",
        subs: {
            manifesto: "Our Philosophy",
            privacy: "Zero-Knowledge Proof",
            settings: "Preferences",
            account: "Account Details",
            aboutUs: "Meet the Founder",
            social: "Connect X/Twitter"
        },
        account_email: "Email Address",
        account_reset: "Reset Password",
        account_reset_desc: "Click below to receive a password reset link via email",
        account_reset_sent: "Password reset email sent! Check your inbox.",
        account_reset_error: "Failed to send reset email",
        premium: "Premium Subscription",
        premium_desc: "Unlock AI-powered features and priority support",
        subscribe_btn: "SUBSCRIBE",
        subscribed_btn: "SUBSCRIBED",
        manage_btn: "MANAGE SUBSCRIPTION",
        billing_history: "Billing History",
        payment_methods: "Payment Methods",
        cancel_subscription: "Cancel Subscription",
        confirm_charge: "CONFIRM CHARGE",
        save_payment: "Save payment method",
        promo_code: "Promotion Code",
        promo_placeholder: "Enter 8-character code",
        card_number: "Card Number",
        card_name: "Cardholder Name",
        card_expiry: "Expiry (MM/YY)",
        card_cvv: "CVV",
        billing_zip: "Billing ZIP Code",
        cancel_warning: "Are you sure you want to cancel your subscription?",
        cancel_confirm: "CONFIRM CANCELLATION",
        no_billing_history: "No billing history yet",
        promo_invalid: "Invalid or already used promotion code",
        promo_success: "Promotion code applied successfully!",
        amount_label: "Amount",
        period_label: "Period",
        date_label: "Date",
        status_label: "Status",
        manage_subscription: "MANAGE SUBSCRIPTION",
        loading_text: "LOADING...",
        subscription_activated: "Subscription activated! Charged",
        promo_activated: "Promo code activated successfully!",
        subscription_failed: "Subscription failed",
        error_occurred: "An error occurred. Please try again.",
        subscription_cancelled: "Subscription cancelled successfully",
        cancellation_failed: "Cancellation failed",
        active_subscription_note: "You already have an active subscription. You can update your payment method below.",
        promo_first_time_note: "Note: Promotion codes can only be used when first subscribing.",
        cancel_subscription_question: "Are you sure you want to cancel your subscription?",
        trial_end_message: "Your free trial will end on the date below. No charges will apply.",
        promo_end_message: "Your promo period will end on the date below. No charges will apply.",
        billing_end_message: "Your premium features will remain active until the end of your current billing period.",
        trial_ends: "Trial ends",
        promo_expires: "Promo expires",
        current_period_ends: "Current period ends",
        resubscribe_note: "After cancellation, you can resubscribe at any time.",
        payment_used: "Payment",
        promo_code_label: "Promo Code",
        status_subscribed: "SUBSCRIBED",
        status_trial_ended: "TRIAL ENDED",
        status_promo: "PROMO",
        status_renewed: "RENEWED",
        status_cancelled: "CANCELLED",
        promo_label: "(PROMO)",
        promo_only_new: "(Only for new subscriptions)",
        promo_not_available: "NOT AVAILABLE",
        promo_enter_code: "ENTER CODE",
        promo_can_only_first: "Promotion codes can only be used when first subscribing",
        promo_using_optional: "Using promo code - card info optional",
        promo_leave_blank: "Leave blank to pay with card",
        card_info: "Card Information",
        card_info_optional: "Card Information (Optional)",
        invalid_card: "Invalid card number",
        invalid_expiry: "Invalid or expired date",
        cvv_must_be: "CVV must be",
        cvv_digits: "digits",
        amex_4_digits: "(4 digits)",
        activate_promo: "ACTIVATE WITH PROMO CODE",
        payment_secure: "Payment is encrypted and secure",
        alert_enter_name: "Please enter cardholder name",
        alert_valid_card: "Please enter a valid card number",
        alert_valid_expiry: "Please enter a valid expiry date",
        alert_valid_cvv: "Please enter a valid CVV",
        alert_billing_zip: "Please enter billing ZIP code",
        alert_unsupported_card: "Unsupported card type",
        period_to: "to"
    },
    sense: {
        title: "SENSE",
        subtitle: "Signal Processing • Entity Decode",
        searchLabel: "SEARCH COMPANY, ENTITY, OR INDIVIDUAL",
        placeholder: "E.g. ELON MUSK, NIKE...",
        run: "SCAN",
        scan_hint: "Type to search or leave empty to scan with camera",
        loading: "COMPILING DOSSIER...",
        loading_image: "Searching dossier for image-identified",
        report: "INTELLIGENCE REPORT",
        summary: "Executive Summary",
        friction: "Friction Points",
        resonance: "Resonance Points",
        socialWire: "SOCIAL WIRE (X)",
        source: "Source Material",
        btn_union: "Check Union",
        btn_context: "View Context",
        btn_recal: "Recalibrate My Stance",
        alternatives: "Consider instead:",
        camera_title: "PRODUCT SCAN",
        camera_subtitle: "Point camera at branded product",
        camera_capture: "CAPTURE",
        camera_retake: "RETAKE",
        camera_confirm: "ANALYZE",
        camera_close: "CLOSE",
        camera_analyzing: "IDENTIFYING BRAND...",
        camera_no_brand: "NO BRAND DETECTED",
        camera_no_brand_desc: "Unable to identify the product manufacturer. Try capturing a clearer image of the brand logo.",
        camera_low_confidence: "LOW CONFIDENCE",
        camera_low_confidence_desc: "Brand identification uncertain. Proceeding with best match.",
        camera_error: "CAMERA ERROR",
        camera_permission: "Camera access required"
    },
    union: {
        title: "THE UNION",
        subtitle: "Collective Action • Decentralized Power",
        network: "Network",
        your_did: "Your DID",
        live: "LIVE",
        active_allies: "Active Allies Online",
        active_desc: "Real-time count of users in your region currently aligning their consumption.",
        active_fronts: "ACTIVE FRONTS",
        view_all: "VIEW ALL",
        target: "TARGET",
        joined: "JOINED",
        goal: "GOAL",
        your_impact: "YOUR IMPACT",
        ledger: "Personal Ledger",
        camp_stat: "Campaigns",
        streak_stat: "Streak",
        redirect_stat: "Redirected",
        amplified: "AMPLIFIED BY THE UNION",
        union_strength: "Total Union Strength",
        capital_divested: "Capital Divested",
        divested_desc: "Estimated revenue denied to conflicting entities this quarter."
    },
    duel: {
        title: "DUEL ARENA",
        subtitle: "Skill-Based Head-to-Head Challenge",
        lobby_title: "DUEL LOBBY",
        arena_title: "DUEL ARENA",
        enter_duel: "ENTER DUEL",
        how_it_works: "HOW IT WORKS",
        compliance_title: "Skill-Based Competition",
        compliance_desc: "Entry fee is for gameplay access. Withdrawals supported.",
        persona: "Persona",
        balance: "Balance",
        entry_fee: "Entry Fee",
        fee: "fee",
        safety_belt: "Safety Belt",
        safety_belt_desc: "If you lose, only half of entry fee is deducted",
        find_opponent: "Find Opponent",
        scanning: "Scanning Network...",
        persona_mismatch: "Finding Opposing Values",
        match_found: "Match Found",
        you: "YOU",
        opponent: "OPPONENT",
        syncing: "Synchronizing Game State...",
        get_ready: "GET READY",
        starting: "Starting...",
        ping_mismatch: "Connection mismatch. Rematching...",
        matchmaking_failed: "Matchmaking failed. Please try again.",
        too_slow: "TOO SLOW!",
        opponent_first: "OPPONENT ANSWERED FIRST",
        no_points: "No points awarded",
        waiting: "WAITING...",
        waiting_opponent: "Waiting for opponent to answer",
        sec: "Sec",
        them: "Them",
        victory: "VICTORY",
        defeat: "DEFEAT",
        draw: "DRAW",
        net_result: "Net Result",
        safety_saved: "Safety Belt Saved",
        rematch: "Rematch",
        back_to_lobby: "Back to Lobby",
        victory_reward: "Victory Reward",
        funds_deducted: "Funds Deducted",
        draw_refunded: "Draw - Refunded",
        entry_card_title: "DUEL ARENA",
        entry_card_subtitle: "Skill-based challenge",
        entry_card_live: "LIVE",
        entry_card_matched: "Matched by stance",
        entry_card_credits: "Credits only",
        duel_mode: "DUEL MODE",
        pvp_arena: "PVP ARENA",
        preview: "Preview",
        duel_description: "Skill-based picture trivia. Challenge opposing personas. Win rewards.",
        fast: "FAST",
        global: "GLOBAL",
        safe: "SAFE",
        enter_arena: "ENTER ARENA",
        duration: "Duration",
        searching: "SEARCHING",
        finding_opponent: "Finding an opponent with opposing views...",
        match_result: "Match Result",
        result: "RESULT",
        notice: "NOTICE",
        low: "Low",
        high: "High",
        wallet_title: "WALLET",
        current_balance: "Current Balance",
        deposit: "Deposit",
        withdraw: "Withdraw",
        select_amount: "Select Amount",
        confirm_deposit: "Confirm Deposit",
        confirm_withdraw: "Confirm Withdraw",
        payment_note: "Simulates external payment gateway",
        insufficient_balance: "Insufficient balance",
        safety_belt_active: "Safety Belt",
        time_up: "TIME UP!",
        calculating: "Calculating results..."
    },
    feed: {
        market: "Values Market Alignment",
        market_title: "THE MARKET",
        market_subtitle: "REAL-TIME VALUES TRACKING",
        aligned_with: "Aligned with",
        curated_for: "Curated for",
        company_ranking: "Values Company Ranking",
        support_companies: "SUPPORT",
        support_companies_tooltip: "Top Aligned Stocks · Buy to Support Your Values",
        oppose_companies: "OPPOSE",
        oppose_companies_tooltip: "Most Opposed Stocks · Avoid or Short These",
        loading_rankings: "ANALYZING COMPANIES...",
        onboarding_required_market: "Complete onboarding to see aligned stocks",
        onboarding_required_rankings: "Complete onboarding to see aligned companies",
        onboarding_required_news: "Complete your stance calibration to get personalized news",
        title: "THE FEED",
        subtitle: "GLOBAL INTELLIGENCE STREAM",
        lens: "PRISM LENS",
        close_lens: "CLOSE LENS",
        loading_lens: "REFRACTING PERSPECTIVES...",
        support: "SUPPORT",
        neutral: "NEUTRAL",
        oppose: "OPPOSE",
        index_return: "Today's Return (Long/Short Equity)",
        index_return_tooltip: "Long Top 5 Aligned · Short Bottom 5 Opposed · Equal Weight",
        updated: "Updated",
        portfolio_index: "Political Values Index",
        portfolio_index_tooltip: "Selected via ESG · News Sentiment · Lobbying · Executive Donations aligned to your Economic · Social · Diplomatic stance",
        performance_tooltip: "Long/Short Equity Strategy: Buy stocks that align with your values, short stocks that oppose them. Portfolio return = average of long position gains + gains from short position declines.",
        persona_tooltip: "Your political persona is determined by your questionnaire responses. Company rankings are based on: ESG scores, FEC political donations, executive public statements, and news sentiment analysis.",
        market_signal: "MARKET SIGNAL",
        representative_positions: "REPRESENTATIVE POSITIONS",
        why_today: "TODAY'S ANALYSIS",
        long_aligned: "LONG (Aligned)",
        short_opposed: "SHORT (Opposed)",
        economic_axis: "Economic Axis",
        social_axis: "Social Axis",
        diplomatic_axis: "Diplomatic Axis",
        left: "Left",
        right: "Right",
        progressive: "Progressive",
        conservative: "Conservative",
        global: "Global",
        national: "National",
        analyzing_market: "Analyzing market movements...",
        analysis_placeholder: "Market analysis will appear here",
        outperforming: "OUTPERFORMING",
        underperforming: "UNDERPERFORMING",
        today_long_short: "today (Long / Short Equity)"
    },
    fingerprint: {
        title: "YOUR STANCE",
        subtitle: "DYNAMIC POLITICAL FINGERPRINT",
        computing: "COMPUTING",
        identified: "IDENTIFIED PERSONA",
        loading: "TRIANGULATING VECTORS...",
        analyzing: "ANALYZING COMPLEXITY...",
        econ: "Economic",
        soc: "Social",
        diplo: "Diplomatic",
        left: "LEFT",
        right: "RIGHT",
        auth: "AUTH",
        lib: "LIB",
        nat: "NAT",
        global: "GLOBAL",
        axis_econ: "Economic Axis",
        axis_soc: "Social Axis",
        axis_diplo: "Diplomatic Axis",
        label_right: "RIGHT",
        label_left: "LEFT",
        label_liberal: "LIBERAL",
        label_conservative: "CONSERVATIVE",
        label_globalist: "GLOBALIST",
        label_nationalist: "NATIONALIST",
        explain_econ_right: "Free market capitalism, deregulation, low taxes, private enterprise",
        explain_econ_left: "Government intervention, regulation, wealth redistribution, public services",
        explain_soc_lib: "Progressive values, personal freedom, diversity, social change",
        explain_soc_auth: "Traditional values, social order, cultural preservation, stability",
        explain_diplo_global: "International cooperation, multilateralism, free trade, global engagement",
        explain_diplo_nat: "National sovereignty, domestic priority, protectionism, independence",
        explain_close: "Click anywhere outside to close",
        reset_stance: "RESET STANCE",
        reset_desc: "Retake & Recalibrate"
    },
    settings: {
        title: "SYSTEM PREFS",
        notifications: "PUSH NOTIFICATIONS",
        loc: "LOCATION SERVICES",
        strict: "STRICT MODE",
        reset_all_settings: "RESET ALL STANSE SETTINGS",
        reset_all_desc: "Reset all preferences and retake questionnaire",
        demo: "DEMO MODE",
        delete: "Delete Account & Wipe Local Data",
        sub_notif: "Alerts for campaign updates",
        sub_loc: "For local store scanning only",
        sub_strict: "Warn on 'Neutral' alignment",
        sub_demo: "Include dummy users in Union data",
        camera: "CAMERA ACCESS",
        sub_camera: "For product scanning",
        camera_enabled: "Camera enabled",
        camera_denied: "Camera access denied",
        camera_pending: "Requesting access...",
        language: "LANGUAGE",
        language_en: "English",
        language_zh: "中文",
        language_ja: "日本語",
        language_fr: "Français",
        language_es: "Español"
    },
    tour: {
        tap_anywhere: "Tap anywhere to continue",
        skip: "Skip Tour",
        back: "BACK",
        next: "NEXT",
        finish: "FINISH"
    },
    manifesto: {
        title: "MANIFESTO",
        subtitle: "The Philosophy of Stanse",
        p1_title: "SILENT VOTING",
        p1_body: "We believe that every dollar spent is a vote cast. Traditional democracy happens every few years; economic democracy happens every day. Your wallet is your ballot box.",
        p2_title: "DATA SOVEREIGNTY",
        p2_body: "In an age of surveillance capitalism, we build tools that serve the user, not the advertiser. We calculate your values locally. We do not sell your political profile.",
        p3_title: "COLLECTIVE ACTION",
        p3_body: "Individual choices feel small, but aggregated action moves markets. Stanse is not just a mirror for self-reflection; it is a lens for collective focus.",
        footer: "DON'T JUST VOTE. LIVE YOUR VALUES."
    },
    privacy: {
        title: "ZERO KNOWLEDGE",
        subtitle: "PRIVACY ARCHITECTURE",
        card_title: "WE DON'T KNOW WHO YOU ARE",
        card_body: "We use Zero-Knowledge Proofs to verify your alignment with campaigns without ever accessing your actual political coordinates or transaction history.",
        local_title: "LOCAL COMPUTATION",
        local_body: "Your \"Political Fingerprint\" is generated and stored exclusively on your device.",
        diff_title: "DIFFERENTIAL PRIVACY",
        diff_body: "When you join a Union Campaign, we add random noise to the data, ensuring your individual contribution cannot be isolated."
    },
    aboutUs: {
        title: "ABOUT US",
        subtitle: "Meet the Founder",
        founder_title: "FOUNDER",
        founder_name: "Lingxiao Xu",
        founder_bio: "Lingxiao, a Senior Quantitative Strategist, Vice President (VP) at Goldman Sachs, holds an MBA degree from Yale University's School of Management and graduated from the Columbia School of Engineering's Department of IEOR. Prior to this role, Lingxiao managed trades in the Equity Structured Derivatives Group at UBS Investment Bank and has also worked with Bank of America Merrill Lynch Group. Lingxiao is the Champion Winner of the Goldman Sachs Global Engineering Hackathon in 2024."
    }
  },
  [Language.ZH]: {
    slogan: "不只投票，更要活出你的价值观。",
    nav: { feed: "动态", sense: "感知", stance: "立场", union: "联合" },
    login: {
        title: "身份识别",
        email: "电子邮箱",
        key: "访问密钥",
        btn: "建立连接",
        google: "通过 GOOGLE 继续",
        protocol: "零知识证明协议",
        sign_up_prompt: "还没有账户？注册",
        sign_in_prompt: "已有账户？登录",
        encrypted_channel: "加密通道"
    },
    menu: {
        manifesto: "宣言",
        privacy: "隐私",
        settings: "设置",
        account: "账户",
        aboutUs: "关于开发者",
        social: "社交媒体",
        logout: "登出",
        subs: {
            manifesto: "我们的哲学",
            privacy: "零知识证明",
            settings: "偏好设置",
            account: "账户详情",
            aboutUs: "认识创始人",
            social: "连接 X/Twitter"
        },
        account_email: "电子邮箱",
        account_reset: "重置密码",
        account_reset_desc: "点击下方按钮，通过电子邮件接收密码重置链接",
        account_reset_sent: "密码重置邮件已发送！请查收邮箱。",
        account_reset_error: "发送重置邮件失败",
        premium: "高级订阅",
        premium_desc: "解锁 AI 功能和优先支持",
        subscribe_btn: "订阅",
        subscribed_btn: "已订阅",
        manage_btn: "管理订阅",
        billing_history: "账单历史",
        payment_methods: "支付方式",
        cancel_subscription: "取消订阅",
        confirm_charge: "确认付款",
        save_payment: "保存支付方式",
        promo_code: "促销码",
        promo_placeholder: "输入8位促销码",
        card_number: "卡号",
        card_name: "持卡人姓名",
        card_expiry: "到期日期 (MM/YY)",
        card_cvv: "安全码",
        billing_zip: "账单邮编",
        cancel_warning: "确定要取消订阅吗？",
        cancel_confirm: "确认取消",
        no_billing_history: "暂无账单历史",
        promo_invalid: "无效或已使用的促销码",
        promo_success: "促销码应用成功！",
        amount_label: "金额",
        period_label: "周期",
        date_label: "日期",
        status_label: "状态",
        manage_subscription: "管理订阅",
        loading_text: "加载中...",
        subscription_activated: "订阅已激活！已收费",
        promo_activated: "促销码激活成功！",
        subscription_failed: "订阅失败",
        error_occurred: "发生错误，请重试。",
        subscription_cancelled: "订阅已成功取消",
        cancellation_failed: "取消失败",
        active_subscription_note: "您已有有效订阅。您可以在下方更新支付方式。",
        promo_first_time_note: "注意：促销码仅在首次订阅时可用。",
        cancel_subscription_question: "确定要取消订阅吗？",
        trial_end_message: "您的免费试用将在下方日期结束。不会产生任何费用。",
        promo_end_message: "您的促销期将在下方日期结束。不会产生任何费用。",
        billing_end_message: "您的高级功能将保持激活状态，直到当前账单周期结束。",
        trial_ends: "试用结束",
        promo_expires: "促销到期",
        current_period_ends: "当前周期结束",
        resubscribe_note: "取消后，您可以随时重新订阅。",
        payment_used: "支付方式",
        promo_code_label: "促销码",
        status_subscribed: "已订阅",
        status_trial_ended: "试用已结束",
        status_promo: "促销",
        status_renewed: "已续订",
        status_cancelled: "已取消",
        promo_label: "(促销)",
        promo_only_new: "(仅限新订阅)",
        promo_not_available: "不可用",
        promo_enter_code: "输入代码",
        promo_can_only_first: "促销码仅在首次订阅时可用",
        promo_using_optional: "使用促销码 - 卡信息可选",
        promo_leave_blank: "留空以使用卡支付",
        card_info: "卡信息",
        card_info_optional: "卡信息（可选）",
        invalid_card: "无效的卡号",
        invalid_expiry: "无效或已过期",
        cvv_must_be: "CVV必须是",
        cvv_digits: "位数字",
        amex_4_digits: "(4位数字)",
        activate_promo: "使用促销码激活",
        payment_secure: "支付已加密且安全",
        alert_enter_name: "请输入持卡人姓名",
        alert_valid_card: "请输入有效的卡号",
        alert_valid_expiry: "请输入有效的到期日期",
        alert_valid_cvv: "请输入有效的CVV",
        alert_billing_zip: "请输入账单邮编",
        alert_unsupported_card: "不支持的卡类型",
        period_to: "至"
    },
    sense: {
        title: "感知引擎",
        subtitle: "信号处理 • 实体解码",
        searchLabel: "搜索公司、实体或个人",
        placeholder: "例如：马斯克, 耐克...",
        run: "扫描",
        scan_hint: "输入文字搜索，或留空使用相机扫描",
        loading: "正在编制档案...",
        loading_image: "正在搜索图片识别出的",
        report: "情报报告",
        summary: "执行摘要",
        friction: "冲突点",
        resonance: "共鸣点",
        socialWire: "社交讯号 (X)",
        source: "情报来源",
        btn_union: "检查联合状态",
        btn_context: "查看背景",
        btn_recal: "重新校准立场",
        alternatives: "替代建议：",
        camera_title: "商品扫描",
        camera_subtitle: "将摄像头对准品牌商品",
        camera_capture: "拍照",
        camera_retake: "重拍",
        camera_confirm: "分析",
        camera_close: "关闭",
        camera_analyzing: "正在识别品牌...",
        camera_no_brand: "未检测到品牌",
        camera_no_brand_desc: "无法识别商品的制造商。请尝试拍摄更清晰的品牌标志图像。",
        camera_low_confidence: "识别置信度较低",
        camera_low_confidence_desc: "品牌识别不确定，将使用最佳匹配结果继续。",
        camera_error: "摄像头错误",
        camera_permission: "需要摄像头访问权限"
    },
    union: {
        title: "联合阵线",
        subtitle: "集体行动 • 去中心化力量",
        network: "网络",
        your_did: "你的DID",
        live: "实时",
        active_allies: "在线盟友",
        active_desc: "当前你所在区域正在实践消费对齐的用户数量。",
        active_fronts: "活跃前线",
        view_all: "查看全部",
        target: "目标",
        joined: "已加入",
        goal: "目标",
        your_impact: "你的影响",
        ledger: "个人账本",
        camp_stat: "战役",
        streak_stat: "连续",
        redirect_stat: "已转移",
        amplified: "联合阵线放大效应",
        union_strength: "联合总力量",
        capital_divested: "撤资总额",
        divested_desc: "本季度估计已拒绝流向冲突实体的收入。"
    },
    duel: {
        title: "对战竞技场",
        subtitle: "技能型一对一挑战",
        lobby_title: "对战大厅",
        arena_title: "对战竞技场",
        enter_duel: "进入对战",
        how_it_works: "玩法说明",
        compliance_title: "技能型竞技",
        compliance_desc: "入场费用于游戏体验。支持提现。",
        persona: "政治画像",
        balance: "余额",
        entry_fee: "入场费",
        fee: "费用",
        safety_belt: "安全带",
        safety_belt_desc: "若失败，仅扣除一半入场费",
        find_opponent: "寻找对手",
        scanning: "扫描网络中...",
        persona_mismatch: "寻找不同价值观对手",
        match_found: "找到对手",
        you: "你",
        opponent: "对手",
        syncing: "同步游戏状态...",
        get_ready: "准备就绪",
        starting: "游戏开始...",
        ping_mismatch: "网络延迟差异过大，重新匹配...",
        matchmaking_failed: "匹配失败，请重试",
        too_slow: "太慢了！",
        opponent_first: "对手抢先作答",
        no_points: "无得分",
        waiting: "等待中...",
        waiting_opponent: "等待对手作答",
        sec: "秒",
        them: "对方",
        victory: "胜利",
        defeat: "失败",
        draw: "平局",
        net_result: "净收益",
        safety_saved: "安全带保护",
        rematch: "再来一局",
        back_to_lobby: "返回大厅",
        victory_reward: "胜利奖励",
        funds_deducted: "资金扣除",
        draw_refunded: "平局 - 已退款",
        entry_card_title: "对战竞技场",
        entry_card_subtitle: "技能型挑战",
        entry_card_live: "实时",
        entry_card_matched: "按立场匹配",
        entry_card_credits: "仅限Credits",
        duel_mode: "对战模式",
        pvp_arena: "PVP竞技场",
        preview: "预览",
        duel_description: "技能型图片问答。挑战对立阵营。赢取奖励。",
        fast: "快速",
        global: "全球",
        safe: "安全",
        enter_arena: "进入竞技场",
        duration: "时长",
        searching: "搜索中",
        finding_opponent: "正在寻找持不同观点的对手...",
        match_result: "比赛结果",
        result: "结果",
        notice: "提示",
        low: "低",
        high: "高",
        wallet_title: "钱包",
        current_balance: "当前余额",
        deposit: "充值",
        withdraw: "提现",
        select_amount: "选择金额",
        confirm_deposit: "确认充值",
        confirm_withdraw: "确认提现",
        payment_note: "模拟外部支付网关",
        insufficient_balance: "余额不足",
        safety_belt_active: "安全带保护",
        time_up: "时间到！",
        calculating: "正在计算结果..."
    },
    feed: {
        market: "价值观市场对齐度",
        market_title: "市场",
        market_subtitle: "实时价值观追踪",
        aligned_with: "对齐",
        curated_for: "为您筛选",
        company_ranking: "价值观公司排名",
        support_companies: "支持",
        support_companies_tooltip: "价值观最匹配 · 买入支持理念",
        oppose_companies: "抵制",
        oppose_companies_tooltip: "价值观最对立 · 回避或做空",
        loading_rankings: "正在分析公司...",
        onboarding_required_market: "完成入职问卷以查看匹配股票",
        onboarding_required_rankings: "完成入职问卷以查看匹配公司",
        onboarding_required_news: "完成立场校准以获取个性化新闻",
        title: "情报流",
        subtitle: "全球情报流",
        lens: "三棱镜透视",
        close_lens: "关闭透视",
        loading_lens: "正在折射视角...",
        support: "支持",
        neutral: "中立",
        oppose: "反对",
        index_return: "今日回报（多空股票）",
        index_return_tooltip: "做多前5支持 · 做空后5反对 · 等权配置",
        updated: "更新时间",
        portfolio_index: "政治价值观指数",
        portfolio_index_tooltip: "基于 ESG · 新闻情绪 · 游说记录 · 高管捐款，匹配您的经济 · 社会 · 外交立场",
        performance_tooltip: "多空股票策略：买入符合您价值观的股票，做空与您价值观对立的股票。组合回报 = 多头收益 + 空头收益的平均值。",
        persona_tooltip: "您的政治画像由问卷答案决定。公司排名基于：ESG评分、FEC政治捐款、高管公开声明和新闻情绪分析。",
        market_signal: "市场信号",
        representative_positions: "代表性持仓",
        why_today: "今日解析",
        long_aligned: "做多（匹配）",
        short_opposed: "做空（对立）",
        economic_axis: "经济轴",
        social_axis: "社会轴",
        diplomatic_axis: "外交轴",
        left: "左",
        right: "右",
        progressive: "进步",
        conservative: "保守",
        global: "全球",
        national: "本土",
        analyzing_market: "正在分析市场动态...",
        analysis_placeholder: "市场分析将在此显示",
        outperforming: "指数表现上涨",
        underperforming: "指数表现下跌",
        today_long_short: "今日 (多空策略)"
    },
    fingerprint: {
        title: "你的立场",
        subtitle: "动态政治指纹",
        computing: "计算中",
        identified: "已识别画像",
        loading: "正在三角定位...",
        analyzing: "正在分析复杂性...",
        econ: "经济维度",
        soc: "社会维度",
        diplo: "外交维度",
        left: "左翼",
        right: "右翼",
        auth: "权威",
        lib: "自由",
        nat: "本土",
        global: "全球",
        axis_econ: "经济轴",
        axis_soc: "社会轴",
        axis_diplo: "外交轴",
        label_right: "右翼",
        label_left: "左翼",
        label_liberal: "自由派",
        label_conservative: "保守派",
        label_globalist: "全球主义",
        label_nationalist: "民族主义",
        explain_econ_right: "自由市场资本主义，放松管制，低税收，私营企业",
        explain_econ_left: "政府干预，监管，财富再分配，公共服务",
        explain_soc_lib: "进步价值观，个人自由，多元化，社会变革",
        explain_soc_auth: "传统价值观，社会秩序，文化保护，稳定性",
        explain_diplo_global: "国际合作，多边主义，自由贸易，全球参与",
        explain_diplo_nat: "国家主权，国内优先，保护主义，独立性",
        explain_close: "点击外部任意位置关闭",
        reset_stance: "重置立场",
        reset_desc: "重新测评和校准"
    },
    settings: {
        title: "系统偏好",
        notifications: "推送通知",
        loc: "定位服务",
        strict: "严格模式",
        reset_all_settings: "重置所有 STANSE 设置",
        reset_all_desc: "重置所有偏好并重新进行问卷",
        demo: "演示模式",
        delete: "删除账户并清除本地数据",
        sub_notif: "战役更新提醒",
        sub_loc: "仅用于本地商店扫描",
        sub_strict: "对'中立'对齐发出警告",
        sub_demo: "联合数据包含演示用户",
        camera: "摄像头权限",
        sub_camera: "用于产品扫描",
        camera_enabled: "摄像头已启用",
        camera_denied: "摄像头权限被拒绝",
        camera_pending: "正在请求权限...",
        language: "语言",
        language_en: "English",
        language_zh: "中文",
        language_ja: "日本語",
        language_fr: "Français",
        language_es: "Español"
    },
    tour: {
        tap_anywhere: "点击屏幕任意位置继续",
        skip: "跳过导览",
        back: "返回",
        next: "下一步",
        finish: "完成"
    },
    manifesto: {
        title: "宣言",
        subtitle: "Stanse 的哲学",
        p1_title: "无声投票",
        p1_body: "我们相信每一次消费都是一次投票。传统的民主几年才发生一次；经济民主每天都在发生。你的钱包就是你的投票箱。",
        p2_title: "数据主权",
        p2_body: "在监控资本主义时代，我们构建服务于用户而非广告商的工具。我们在本地计算你的价值观，绝不出售你的政治画像。",
        p3_title: "集体行动",
        p3_body: "个人的选择看似渺小，但聚合的行动可以撼动市场。Stanse 不仅仅是一面自省的镜子，更是集体聚焦的透镜。",
        footer: "不只投票，更要活出你的价值观。"
    },
    privacy: {
        title: "零知识",
        subtitle: "隐私架构",
        card_title: "我们不知道你是谁",
        card_body: "我们使用零知识证明来验证你与战役的对齐情况，而无需访问你的实际政治坐标或交易历史。",
        local_title: "本地计算",
        local_body: "你的\"政治指纹\"仅在你的设备上生成和存储。",
        diff_title: "差分隐私",
        diff_body: "当你加入联合战役时，我们会向数据中添加随机噪声，确保你的个人贡献无法被隔离识别。"
    },
    aboutUs: {
        title: "关于开发者",
        subtitle: "认识创始人",
        founder_title: "创始人",
        founder_name: "许凌霄",
        founder_bio: "凌霄是高盛集团高级量化策略师、副总裁（VP），拥有耶鲁大学管理学院MBA学位，毕业于哥伦比亚大学工程学院工业工程与运筹学系。在此之前，凌霄在瑞银投资银行股票结构化衍生品组管理交易，还曾在美国银行美林集团工作。凌霄是2024年高盛全球工程黑客马拉松的冠军获得者。"
    }
  },
  [Language.JA]: {
    slogan: "ただ投票するだけでなく、価値観を生きる。",
    nav: { feed: "フィード", sense: "センス", stance: "スタンス", union: "ユニオン" },
    login: {
        title: "本人確認",
        email: "メールアドレス",
        key: "アクセスキー",
        btn: "リンク確立",
        google: "GOOGLEで続行",
        protocol: "ゼロ知識証明プロトコル",
        sign_up_prompt: "アカウントをお持ちでない方は？登録",
        sign_in_prompt: "既にアカウントをお持ちですか？サインイン",
        encrypted_channel: "暗号化チャンネル"
    },
    menu: {
        manifesto: "マニフェスト",
        privacy: "プライバシー",
        settings: "設定",
        account: "アカウント",
        aboutUs: "開発者について",
        social: "ソーシャル",
        logout: "ログアウト",
        subs: {
            manifesto: "私たちの哲学",
            privacy: "ゼロ知識証明",
            settings: "環境設定",
            account: "アカウント詳細",
            aboutUs: "創設者に会う",
            social: "X/Twitterを接続"
        },
        account_email: "メールアドレス",
        account_reset: "パスワードをリセット",
        account_reset_desc: "以下をクリックしてパスワードリセットリンクをメールで受け取る",
        account_reset_sent: "パスワードリセットメールを送信しました！受信トレイをご確認ください。",
        account_reset_error: "リセットメールの送信に失敗しました",
        premium: "プレミアムサブスクリプション",
        premium_desc: "AI機能とサポートを解除",
        subscribe_btn: "サブスクライブ",
        subscribed_btn: "購読中",
        manage_btn: "サブスクリプション管理",
        billing_history: "請求履歴",
        payment_methods: "支払い方法",
        cancel_subscription: "サブスクリプションをキャンセル",
        confirm_charge: "支払いを確認",
        save_payment: "支払い方法を保存",
        promo_code: "プロモーションコード",
        promo_placeholder: "8文字のコードを入力",
        card_number: "カード番号",
        card_name: "カード名義人",
        card_expiry: "有効期限 (MM/YY)",
        card_cvv: "セキュリティコード",
        billing_zip: "請求先郵便番号",
        cancel_warning: "サブスクリプションをキャンセルしてもよろしいですか？",
        cancel_confirm: "キャンセルを確認",
        no_billing_history: "請求履歴はまだありません",
        promo_invalid: "無効または使用済みのプロモーションコード",
        promo_success: "プロモーションコードが適用されました！",
        amount_label: "金額",
        period_label: "期間",
        date_label: "日付",
        status_label: "ステータス",
        manage_subscription: "サブスクリプション管理",
        loading_text: "読み込み中...",
        subscription_activated: "サブスクリプションが有効化されました！請求額",
        promo_activated: "プロモーションコードが正常に有効化されました！",
        subscription_failed: "サブスクリプションに失敗しました",
        error_occurred: "エラーが発生しました。もう一度お試しください。",
        subscription_cancelled: "サブスクリプションが正常にキャンセルされました",
        cancellation_failed: "キャンセルに失敗しました",
        active_subscription_note: "既にアクティブなサブスクリプションがあります。以下で支払い方法を更新できます。",
        promo_first_time_note: "注意：プロモーションコードは初回サブスクライブ時のみ使用できます。",
        cancel_subscription_question: "サブスクリプションをキャンセルしてもよろしいですか？",
        trial_end_message: "無料トライアルは以下の日付に終了します。料金は発生しません。",
        promo_end_message: "プロモ期間は以下の日付に終了します。料金は発生しません。",
        billing_end_message: "プレミアム機能は現在の請求期間が終了するまでアクティブのまま残ります。",
        trial_ends: "トライアル終了",
        promo_expires: "プロモ期限切れ",
        current_period_ends: "現在の期間終了",
        resubscribe_note: "キャンセル後、いつでも再サブスクライブできます。",
        payment_used: "支払い方法",
        promo_code_label: "プロモコード",
        status_subscribed: "サブスクライブ済み",
        status_trial_ended: "トライアル終了",
        status_promo: "プロモ",
        status_renewed: "更新済み",
        status_cancelled: "キャンセル済み",
        promo_label: "(プロモ)",
        promo_only_new: "(新規サブスクリプションのみ)",
        promo_not_available: "利用不可",
        promo_enter_code: "コード入力",
        promo_can_only_first: "プロモーションコードは初回サブスクライブ時のみ使用可能",
        promo_using_optional: "プロモコード使用中 - カード情報はオプション",
        promo_leave_blank: "カードで支払う場合は空白のまま",
        card_info: "カード情報",
        card_info_optional: "カード情報（オプション）",
        invalid_card: "無効なカード番号",
        invalid_expiry: "無効または期限切れ",
        cvv_must_be: "CVVは",
        cvv_digits: "桁である必要があります",
        amex_4_digits: "(4桁)",
        activate_promo: "プロモコードで有効化",
        payment_secure: "支払いは暗号化されており安全です",
        alert_enter_name: "カード名義人を入力してください",
        alert_valid_card: "有効なカード番号を入力してください",
        alert_valid_expiry: "有効な有効期限を入力してください",
        alert_valid_cvv: "有効なCVVを入力してください",
        alert_billing_zip: "請求先郵便番号を入力してください",
        alert_unsupported_card: "サポートされていないカードタイプ",
        period_to: "から"
    },
    sense: {
        title: "センス",
        subtitle: "信号処理 • エンティティ解読",
        searchLabel: "企業、エンティティ、または個人を検索",
        placeholder: "例: イーロン・マスク, ナイキ...",
        run: "スキャン",
        scan_hint: "入力して検索、または空欄のままカメラでスキャン",
        loading: "調査書を作成中...",
        loading_image: "画像識別による検索中",
        report: "インテリジェンスレポート",
        summary: "エグゼクティブサマリー",
        friction: "摩擦点 (不一致)",
        resonance: "共鳴点 (一致)",
        socialWire: "ソーシャルワイヤー (X)",
        source: "情報源",
        btn_union: "ユニオン確認",
        btn_context: "文脈を表示",
        btn_recal: "スタンス再調整",
        alternatives: "代替案の検討：",
        camera_title: "商品スキャン",
        camera_subtitle: "ブランド製品にカメラを向けてください",
        camera_capture: "撮影",
        camera_retake: "撮り直し",
        camera_confirm: "分析",
        camera_close: "閉じる",
        camera_analyzing: "ブランド識別中...",
        camera_no_brand: "ブランド未検出",
        camera_no_brand_desc: "製品のメーカーを識別できません。ブランドロゴの鮮明な画像を撮影してください。",
        camera_low_confidence: "低信頼度",
        camera_low_confidence_desc: "ブランド識別が不確実です。最も可能性の高い結果で続行します。",
        camera_error: "カメラエラー",
        camera_permission: "カメラへのアクセスが必要です"
    },
    union: {
        title: "ザ・ユニオン",
        subtitle: "集団行動 • 分散型権力",
        network: "ネットワーク",
        your_did: "あなたのDID",
        live: "ライブ",
        active_allies: "アクティブな同盟者",
        active_desc: "あなたの地域で現在、消費行動を調整しているユーザーのリアルタイム数。",
        active_fronts: "アクティブな戦線",
        view_all: "すべて表示",
        target: "ターゲット",
        joined: "参加者",
        goal: "目標",
        your_impact: "あなたの影響",
        ledger: "個人台帳",
        camp_stat: "参加数",
        streak_stat: "継続",
        redirect_stat: "転換額",
        amplified: "ユニオンによる増幅",
        union_strength: "ユニオン総力",
        capital_divested: "総撤退資本",
        divested_desc: "今四半期、対立するエンティティへの支払いを拒否した推定額。"
    },
    duel: {
        title: "デュエルアリーナ",
        subtitle: "スキルベース1対1チャレンジ",
        lobby_title: "デュエルロビー",
        arena_title: "デュエルアリーナ",
        enter_duel: "デュエル参加",
        how_it_works: "遊び方",
        compliance_title: "スキルベース競技",
        compliance_desc: "参加費はゲーム体験用。出金対応。",
        persona: "政治ペルソナ",
        balance: "残高",
        entry_fee: "参加費",
        fee: "料金",
        safety_belt: "セーフティベルト",
        safety_belt_desc: "負けた場合、参加費の半額のみ控除",
        find_opponent: "対戦相手を探す",
        scanning: "ネットワークスキャン中...",
        persona_mismatch: "対立する価値観を探索中",
        match_found: "対戦相手発見",
        you: "あなた",
        opponent: "対戦相手",
        syncing: "ゲーム状態同期中...",
        get_ready: "準備完了",
        starting: "開始中...",
        ping_mismatch: "接続ミスマッチ。再マッチング...",
        matchmaking_failed: "マッチング失敗。再試行してください。",
        too_slow: "遅すぎる！",
        opponent_first: "対戦相手が先に回答",
        no_points: "ポイントなし",
        waiting: "待機中...",
        waiting_opponent: "対戦相手の回答を待っています",
        sec: "秒",
        them: "相手",
        victory: "勝利",
        defeat: "敗北",
        draw: "引き分け",
        net_result: "純収益",
        safety_saved: "セーフティベルト保護",
        rematch: "再戦",
        back_to_lobby: "ロビーに戻る",
        victory_reward: "勝利報酬",
        funds_deducted: "資金控除",
        draw_refunded: "引き分け - 返金",
        entry_card_title: "デュエルアリーナ",
        entry_card_subtitle: "スキルベースチャレンジ",
        entry_card_live: "ライブ",
        entry_card_matched: "スタンス別マッチング",
        entry_card_credits: "クレジットのみ",
        duel_mode: "デュエルモード",
        pvp_arena: "PVPアリーナ",
        preview: "プレビュー",
        duel_description: "スキルベースの画像トリビア。対立する相手に挑戦。報酬を獲得。",
        fast: "高速",
        global: "グローバル",
        safe: "安全",
        enter_arena: "アリーナに入る",
        duration: "時間",
        searching: "検索中",
        finding_opponent: "異なる意見を持つ対戦相手を探しています...",
        match_result: "試合結果",
        result: "結果",
        notice: "通知",
        low: "低",
        high: "高",
        wallet_title: "ウォレット",
        current_balance: "現在の残高",
        deposit: "入金",
        withdraw: "出金",
        select_amount: "金額を選択",
        confirm_deposit: "入金確認",
        confirm_withdraw: "出金確認",
        payment_note: "外部決済ゲートウェイのシミュレーション",
        insufficient_balance: "残高不足",
        safety_belt_active: "セーフティベルト",
        time_up: "タイムアップ！",
        calculating: "結果を計算中..."
    },
    feed: {
        market: "価値観市場適合度",
        market_title: "マーケット",
        market_subtitle: "リアルタイム価値観追跡",
        aligned_with: "適合",
        curated_for: "キュレーション",
        company_ranking: "価値観企業ランキング",
        support_companies: "支持",
        support_companies_tooltip: "価値観最一致 · 買いで理念支持",
        oppose_companies: "反対",
        oppose_companies_tooltip: "価値観最対立 · 回避またはショート",
        loading_rankings: "企業を分析中...",
        onboarding_required_market: "オンボーディングを完了して適合銘柄を表示",
        onboarding_required_rankings: "オンボーディングを完了して適合企業を表示",
        onboarding_required_news: "スタンス較正を完了してパーソナライズされたニュースを取得",
        title: "フィード",
        subtitle: "グローバルインテリジェンス",
        lens: "プリズムレンズ",
        close_lens: "レンズを閉じる",
        loading_lens: "視点を屈折中...",
        support: "支持",
        neutral: "中立",
        oppose: "反対",
        index_return: "本日リターン（ロングショート）",
        index_return_tooltip: "上位5銘柄ロング · 下位5銘柄ショート · 等ウェイト",
        updated: "更新日時",
        portfolio_index: "政治価値観指数",
        portfolio_index_tooltip: "ESG · ニュース感情 · ロビー活動 · 役員献金に基づき、経済 · 社会 · 外交の立場に合致",
        performance_tooltip: "ロング・ショート株式戦略：あなたの価値観に合う銘柄を買い、反する銘柄を空売り。ポートフォリオリターン = ロングポジションの利益 + ショートポジションの利益の平均。",
        persona_tooltip: "あなたの政治的ペルソナはアンケート回答で決定されます。企業ランキングは ESGスコア、FEC政治献金、役員の公開発言、ニュース感情分析に基づきます。",
        market_signal: "マーケットシグナル",
        representative_positions: "代表的ポジション",
        why_today: "本日の分析",
        long_aligned: "ロング（一致）",
        short_opposed: "ショート（対立）",
        economic_axis: "経済軸",
        social_axis: "社会軸",
        diplomatic_axis: "外交軸",
        left: "左派",
        right: "右派",
        progressive: "リベラル",
        conservative: "保守",
        global: "グローバル",
        national: "ナショナル",
        analyzing_market: "市場動向を分析中...",
        analysis_placeholder: "市場分析がここに表示されます",
        outperforming: "上昇中",
        underperforming: "下落中",
        today_long_short: "本日 (ロング/ショート)"
    },
    fingerprint: {
        title: "あなたのスタンス",
        subtitle: "動的政治指紋",
        computing: "計算中",
        identified: "特定されたペルソナ",
        loading: "ベクトル三角測量中...",
        analyzing: "複雑性を分析中...",
        econ: "経済軸",
        soc: "社会軸",
        diplo: "外交軸",
        left: "左派",
        right: "右派",
        auth: "権威",
        lib: "自由",
        nat: "自国",
        global: "国際",
        axis_econ: "経済軸",
        axis_soc: "社会軸",
        axis_diplo: "外交軸",
        label_right: "右派",
        label_left: "左派",
        label_liberal: "リベラル",
        label_conservative: "保守派",
        label_globalist: "グローバリスト",
        label_nationalist: "ナショナリスト",
        explain_econ_right: "自由市場資本主義、規制緩和、低税率、民間企業",
        explain_econ_left: "政府介入、規制、富の再分配、公共サービス",
        explain_soc_lib: "進歩的価値観、個人の自由、多様性、社会変革",
        explain_soc_auth: "伝統的価値観、社会秩序、文化保護、安定性",
        explain_diplo_global: "国際協力、多国間主義、自由貿易、グローバル関与",
        explain_diplo_nat: "国家主権、国内優先、保護主義、独立性",
        explain_close: "外側をクリックして閉じる",
        reset_stance: "スタンスをリセット",
        reset_desc: "再受験と再調整"
    },
    settings: {
        title: "システム設定",
        notifications: "プッシュ通知",
        loc: "位置情報サービス",
        strict: "厳格モード",
        reset_all_settings: "すべての STANSE 設定をリセット",
        reset_all_desc: "すべての設定をリセットしてアンケートを再受験",
        demo: "デモモード",
        delete: "アカウント削除とデータ消去",
        sub_notif: "キャンペーン更新のアラート",
        sub_loc: "ローカル店舗スキャン用",
        sub_strict: "「中立」アライメントに警告",
        sub_demo: "ユニオンデータにダミーユーザーを含む",
        camera: "カメラアクセス",
        sub_camera: "製品スキャン用",
        camera_enabled: "カメラが有効",
        camera_denied: "カメラアクセスが拒否されました",
        camera_pending: "アクセスを要求中...",
        language: "言語",
        language_en: "English",
        language_zh: "中文",
        language_ja: "日本語",
        language_fr: "Français",
        language_es: "Español"
    },
    tour: {
        tap_anywhere: "画面をタップして続ける",
        skip: "ツアーをスキップ",
        back: "戻る",
        next: "次へ",
        finish: "完了"
    },
    manifesto: {
        title: "マニフェスト",
        subtitle: "Stanseの哲学",
        p1_title: "沈黙の投票",
        p1_body: "私たちは、使われるすべてのドルが投票であると信じています。従来の民主主義は数年に一度ですが、経済民主主義は毎日起こります。あなたの財布は投票箱です。",
        p2_title: "データ主権",
        p2_body: "監視資本主義の時代において、私たちは広告主ではなくユーザーに奉仕するツールを構築します。私たちはあなたの価値観をローカルで計算します。政治的プロファイルを販売することはありません。",
        p3_title: "集団行動",
        p3_body: "個人の選択は小さく見えますが、集約された行動は市場を動かします。Stanseは単なる内省のための鏡ではなく、集団的焦点のためのレンズです。",
        footer: "ただ投票するだけでなく、価値観を生きる。"
    },
    privacy: {
        title: "ゼロ知識",
        subtitle: "プライバシーアーキテクチャ",
        card_title: "私たちはあなたが誰かを知りません",
        card_body: "私たちはゼロ知識証明を使用して、実際の政治座標や取引履歴にアクセスすることなく、キャンペーンとの整合性を検証します。",
        local_title: "ローカル計算",
        local_body: "あなたの「政治的指紋」は、あなたのデバイス上でのみ生成および保存されます。",
        diff_title: "差分プライバシー",
        diff_body: "ユニオンキャンペーンに参加すると、データにランダムなノイズが追加され、個人の貢献が特定されないようになります。"
    },
    aboutUs: {
        title: "開発者について",
        subtitle: "創設者に会う",
        founder_title: "創設者",
        founder_name: "许凌霄",
        founder_bio: "凌霄は、ゴールドマン・サックスのシニア・クオンツ・ストラテジスト、ヴァイスプレジデント（VP）であり、イェール大学経営大学院のMBA学位を取得し、コロンビア大学工学部産業工学・オペレーションズリサーチ学科を卒業しました。以前は、UBS投資銀行の株式デリバティブグループで取引を管理し、バンク・オブ・アメリカ・メリルリンチ・グループでも勤務していました。凌霄は2024年ゴールドマン・サックス・グローバル・エンジニアリング・ハッカソンのチャンピオンです。"
    }
  },
  [Language.FR]: {
    slogan: "Ne votez pas juste. Incarnez vos valeurs.",
    nav: { feed: "FLUX", sense: "SENS", stance: "POSITION", union: "UNION" },
    login: {
        title: "IDENTIFICATION",
        email: "EMAIL",
        key: "CLÉ D'ACCÈS",
        btn: "ÉTABLIR LIEN",
        google: "CONTINUER AVEC GOOGLE",
        protocol: "Protocole à Divulgation Nulle",
        sign_up_prompt: "Pas de compte ? S'inscrire",
        sign_in_prompt: "Déjà un compte ? Se connecter",
        encrypted_channel: "CANAL CRYPTÉ"
    },
    menu: {
        manifesto: "MANIFESTE",
        privacy: "CONFIDENTIALITÉ",
        settings: "RÉGLAGES",
        account: "COMPTE",
        aboutUs: "À PROPOS",
        social: "MÉDIAS SOCIAUX",
        logout: "DÉCONNEXION",
        subs: {
            manifesto: "Notre Philosophie",
            privacy: "Preuve Zéro Connaissance",
            settings: "Préférences",
            account: "Détails du Compte",
            aboutUs: "Rencontrer le Fondateur",
            social: "Connecter X/Twitter"
        },
        account_email: "Adresse E-mail",
        account_reset: "Réinitialiser le Mot de Passe",
        account_reset_desc: "Cliquez ci-dessous pour recevoir un lien de réinitialisation par e-mail",
        account_reset_sent: "E-mail de réinitialisation envoyé ! Consultez votre boîte de réception.",
        account_reset_error: "Échec de l'envoi de l'e-mail",
        premium: "Abonnement Premium",
        premium_desc: "Débloquer les fonctionnalités IA et le support prioritaire",
        subscribe_btn: "S'ABONNER",
        subscribed_btn: "ABONNÉ",
        manage_btn: "GÉRER L'ABONNEMENT",
        billing_history: "Historique de Facturation",
        payment_methods: "Méthodes de Paiement",
        cancel_subscription: "Annuler l'Abonnement",
        confirm_charge: "CONFIRMER LE PAIEMENT",
        save_payment: "Enregistrer le moyen de paiement",
        promo_code: "Code Promotionnel",
        promo_placeholder: "Entrez le code à 8 caractères",
        card_number: "Numéro de Carte",
        card_name: "Nom du Titulaire",
        card_expiry: "Expiration (MM/AA)",
        card_cvv: "CVV",
        billing_zip: "Code Postal de Facturation",
        cancel_warning: "Êtes-vous sûr de vouloir annuler votre abonnement?",
        cancel_confirm: "CONFIRMER L'ANNULATION",
        no_billing_history: "Aucun historique de facturation",
        promo_invalid: "Code promotionnel invalide ou déjà utilisé",
        promo_success: "Code promotionnel appliqué avec succès!",
        amount_label: "Montant",
        period_label: "Période",
        date_label: "Date",
        status_label: "Statut",
        manage_subscription: "GÉRER L'ABONNEMENT",
        loading_text: "CHARGEMENT...",
        subscription_activated: "Abonnement activé! Facturé",
        promo_activated: "Code promotionnel activé avec succès!",
        subscription_failed: "Échec de l'abonnement",
        error_occurred: "Une erreur s'est produite. Veuillez réessayer.",
        subscription_cancelled: "Abonnement annulé avec succès",
        cancellation_failed: "Échec de l'annulation",
        active_subscription_note: "Vous avez déjà un abonnement actif. Vous pouvez mettre à jour votre moyen de paiement ci-dessous.",
        promo_first_time_note: "Note : Les codes promotionnels ne peuvent être utilisés que lors du premier abonnement.",
        cancel_subscription_question: "Êtes-vous sûr de vouloir annuler votre abonnement?",
        trial_end_message: "Votre essai gratuit se terminera à la date ci-dessous. Aucun frais ne sera appliqué.",
        promo_end_message: "Votre période promotionnelle se terminera à la date ci-dessous. Aucun frais ne sera appliqué.",
        billing_end_message: "Vos fonctionnalités premium resteront actives jusqu'à la fin de votre période de facturation actuelle.",
        trial_ends: "Fin de l'essai",
        promo_expires: "Expiration de la promo",
        current_period_ends: "Fin de la période actuelle",
        resubscribe_note: "Après l'annulation, vous pouvez vous réabonner à tout moment.",
        payment_used: "Paiement",
        promo_code_label: "Code Promo",
        status_subscribed: "ABONNÉ",
        status_trial_ended: "ESSAI TERMINÉ",
        status_promo: "PROMO",
        status_renewed: "RENOUVELÉ",
        status_cancelled: "ANNULÉ",
        promo_label: "(PROMO)",
        promo_only_new: "(Nouveaux abonnements uniquement)",
        promo_not_available: "NON DISPONIBLE",
        promo_enter_code: "ENTRER LE CODE",
        promo_can_only_first: "Les codes promotionnels ne peuvent être utilisés que lors du premier abonnement",
        promo_using_optional: "Code promo utilisé - infos carte optionnelles",
        promo_leave_blank: "Laisser vide pour payer par carte",
        card_info: "Informations de Carte",
        card_info_optional: "Informations de Carte (Optionnel)",
        invalid_card: "Numéro de carte invalide",
        invalid_expiry: "Date invalide ou expirée",
        cvv_must_be: "CVV doit être",
        cvv_digits: "chiffres",
        amex_4_digits: "(4 chiffres)",
        activate_promo: "ACTIVER AVEC CODE PROMO",
        payment_secure: "Le paiement est crypté et sécurisé",
        alert_enter_name: "Veuillez entrer le nom du titulaire",
        alert_valid_card: "Veuillez entrer un numéro de carte valide",
        alert_valid_expiry: "Veuillez entrer une date d'expiration valide",
        alert_valid_cvv: "Veuillez entrer un CVV valide",
        alert_billing_zip: "Veuillez entrer le code postal de facturation",
        alert_unsupported_card: "Type de carte non supporté",
        period_to: "à"
    },
    sense: {
        title: "SENS",
        subtitle: "Traitement du Signal • Décodage",
        searchLabel: "RECHERCHER ENTREPRISE, ENTITÉ OU INDIVIDU",
        placeholder: "Ex. LVMH, TOTAL...",
        run: "SCANNER",
        scan_hint: "Tapez pour rechercher ou laissez vide pour scanner",
        loading: "COMPILATION DU DOSSIER...",
        loading_image: "Recherche dossier pour image identifiée",
        report: "RAPPORT DE RENSEIGNEMENT",
        summary: "Résumé Exécutif",
        friction: "Points de Friction",
        resonance: "Points de Résonance",
        socialWire: "SIGNAL SOCIAL (X)",
        source: "Sources",
        btn_union: "Vérifier Union",
        btn_context: "Voir Contexte",
        btn_recal: "Recalibrer Position",
        alternatives: "Considérer plutôt :",
        camera_title: "SCAN PRODUIT",
        camera_subtitle: "Visez le produit avec la caméra",
        camera_capture: "CAPTURER",
        camera_retake: "REPRENDRE",
        camera_confirm: "ANALYSER",
        camera_close: "FERMER",
        camera_analyzing: "IDENTIFICATION MARQUE...",
        camera_no_brand: "AUCUNE MARQUE DÉTECTÉE",
        camera_no_brand_desc: "Impossible d'identifier le fabricant. Essayez de capturer une image plus nette du logo.",
        camera_low_confidence: "CONFIANCE FAIBLE",
        camera_low_confidence_desc: "Identification de marque incertaine. Utilisation de la meilleure correspondance.",
        camera_error: "ERREUR CAMÉRA",
        camera_permission: "Accès caméra requis"
    },
    union: {
        title: "L'UNION",
        subtitle: "Action Collective • Pouvoir Décentralisé",
        network: "Réseau",
        your_did: "Votre DID",
        live: "EN DIRECT",
        active_allies: "Alliés Actifs",
        active_desc: "Nombre temps réel d'utilisateurs alignant leur consommation.",
        active_fronts: "FRONTS ACTIFS",
        view_all: "VOIR TOUT",
        target: "CIBLE",
        joined: "REJOINTS",
        goal: "BUT",
        your_impact: "VOTRE IMPACT",
        ledger: "Registre Personnel",
        camp_stat: "Campagnes",
        streak_stat: "Série",
        redirect_stat: "Redirigé",
        amplified: "AMPLIFIÉ PAR L'UNION",
        union_strength: "Force Totale",
        capital_divested: "Capital Désinvesti",
        divested_desc: "Revenu estimé refusé aux entités en conflit ce trimestre."
    },
    duel: {
        title: "ARÈNE DE DUEL",
        subtitle: "Défi Compétences Tête-à-Tête",
        lobby_title: "LOBBY DE DUEL",
        arena_title: "ARÈNE DE DUEL",
        enter_duel: "ENTRER EN DUEL",
        how_it_works: "COMMENT ÇA MARCHE",
        compliance_title: "Compétition Basée sur les Compétences",
        compliance_desc: "Frais d'entrée pour l'accès au jeu. Retraits pris en charge.",
        persona: "Persona",
        balance: "Solde",
        entry_fee: "Frais d'Entrée",
        fee: "frais",
        safety_belt: "Ceinture de Sécurité",
        safety_belt_desc: "En cas de défaite, seulement la moitié des frais d'entrée est déduite",
        find_opponent: "Trouver un Adversaire",
        scanning: "Scan du Réseau...",
        persona_mismatch: "Recherche de Valeurs Opposées",
        match_found: "Match Trouvé",
        you: "VOUS",
        opponent: "ADVERSAIRE",
        syncing: "Synchronisation de l'État du Jeu...",
        ping_mismatch: "Décalage de connexion. Rematch...",
        matchmaking_failed: "Échec du matchmaking. Réessayez.",
        too_slow: "TROP LENT !",
        opponent_first: "ADVERSAIRE A RÉPONDU EN PREMIER",
        sec: "Sec",
        them: "Eux",
        victory: "VICTOIRE",
        defeat: "DÉFAITE",
        draw: "ÉGALITÉ",
        net_result: "Résultat Net",
        safety_saved: "Ceinture Économisé",
        rematch: "Rematch",
        back_to_lobby: "Retour au Lobby",
        victory_reward: "Récompense de Victoire",
        funds_deducted: "Fonds Déduits",
        draw_refunded: "Égalité - Remboursé",
        entry_card_title: "ARÈNE DE DUEL",
        entry_card_subtitle: "Défi basé sur compétences",
        entry_card_live: "EN DIRECT",
        entry_card_matched: "Apparié par position",
        entry_card_credits: "Crédits uniquement",
        duel_mode: "MODE DUEL",
        pvp_arena: "ARÈNE PVP",
        preview: "Aperçu",
        duel_description: "Trivia d'images basé sur les compétences. Défiez les personas adverses. Gagnez des récompenses.",
        fast: "RAPIDE",
        global: "GLOBAL",
        safe: "SÛR",
        enter_arena: "ENTRER DANS L'ARÈNE",
        duration: "Durée",
        searching: "RECHERCHE",
        finding_opponent: "Recherche d'un adversaire aux opinions opposées...",
        match_result: "Résultat du Match",
        result: "RÉSULTAT",
        notice: "AVIS",
        low: "Bas",
        high: "Haut",
        wallet_title: "PORTEFEUILLE",
        current_balance: "Solde Actuel",
        deposit: "Dépôt",
        withdraw: "Retrait",
        select_amount: "Sélectionner le Montant",
        confirm_deposit: "Confirmer le Dépôt",
        confirm_withdraw: "Confirmer le Retrait",
        payment_note: "Simule une passerelle de paiement externe",
        insufficient_balance: "Solde insuffisant",
        safety_belt_active: "Ceinture de Sécurité",
        time_up: "TEMPS ÉCOULÉ !",
        calculating: "Calcul des résultats..."
    },
    feed: {
        market: "Alignement Marché Valeurs",
        market_title: "LE MARCHÉ",
        market_subtitle: "SUIVI DES VALEURS EN TEMPS RÉEL",
        aligned_with: "Aligné avec",
        curated_for: "Sélectionné pour",
        company_ranking: "Classement des Entreprises selon les Valeurs",
        support_companies: "SOUTENIR",
        support_companies_tooltip: "Actions les Plus Alignées · Achat pour Soutenir",
        oppose_companies: "S'OPPOSER",
        oppose_companies_tooltip: "Actions les Plus Opposées · Éviter ou Vendre",
        loading_rankings: "ANALYSE DES ENTREPRISES...",
        onboarding_required_market: "Complétez l'intégration pour voir les actions alignées",
        onboarding_required_rankings: "Complétez l'intégration pour voir les entreprises alignées",
        onboarding_required_news: "Complétez votre calibrage de position pour obtenir des nouvelles personnalisées",
        title: "LE FLUX",
        subtitle: "FLUX DE RENSEIGNEMENT GLOBAL",
        lens: "LENTILLE PRISME",
        close_lens: "FERMER LENTILLE",
        loading_lens: "RÉFRACTION DES PERSPECTIVES...",
        support: "POUR",
        neutral: "NEUTRE",
        oppose: "CONTRE",
        index_return: "Rendement du Jour (Long/Short)",
        index_return_tooltip: "Long Top 5 Alignées · Short Bottom 5 Opposées · Pondération Égale",
        updated: "Mis à jour",
        portfolio_index: "Indice Valeurs Politiques",
        portfolio_index_tooltip: "Sélection via ESG · Sentiment Médias · Lobbying · Dons Dirigeants selon vos axes Économique · Social · Diplomatique",
        performance_tooltip: "Stratégie Long/Short Actions : Acheter des actions alignées avec vos valeurs, vendre à découvert celles opposées. Rendement du portefeuille = moyenne des gains long + gains short.",
        persona_tooltip: "Votre persona politique est déterminé par vos réponses au questionnaire. Le classement des entreprises est basé sur : scores ESG, dons politiques FEC, déclarations publiques des dirigeants et analyse du sentiment des médias.",
        market_signal: "SIGNAL DE MARCHÉ",
        representative_positions: "POSITIONS REPRÉSENTATIVES",
        why_today: "ANALYSE DU JOUR",
        long_aligned: "LONG (Aligné)",
        short_opposed: "SHORT (Opposé)",
        economic_axis: "Axe Économique",
        social_axis: "Axe Social",
        diplomatic_axis: "Axe Diplomatique",
        left: "Gauche",
        right: "Droite",
        progressive: "Progressiste",
        conservative: "Conservateur",
        global: "Mondial",
        national: "National",
        analyzing_market: "Analyse des mouvements du marché...",
        analysis_placeholder: "L'analyse du marché apparaîtra ici",
        outperforming: "EN HAUSSE",
        underperforming: "EN BAISSE",
        today_long_short: "aujourd'hui (Long / Short)"
    },
    fingerprint: {
        title: "VOTRE POSITION",
        subtitle: "EMPREINTE POLITIQUE DYNAMIQUE",
        computing: "CALCUL",
        identified: "PERSONA IDENTIFIÉ",
        loading: "TRIANGULATION...",
        analyzing: "ANALYSE COMPLEXITÉ...",
        econ: "Économique",
        soc: "Social",
        diplo: "Diplomatique",
        left: "GAUCHE",
        right: "DROITE",
        auth: "AUTH",
        lib: "LIB",
        nat: "NAT",
        global: "MONDE",
        axis_econ: "Axe Économique",
        axis_soc: "Axe Social",
        axis_diplo: "Axe Diplomatique",
        label_right: "DROITE",
        label_left: "GAUCHE",
        label_liberal: "LIBÉRAL",
        label_conservative: "CONSERVATEUR",
        label_globalist: "MONDIALISTE",
        label_nationalist: "NATIONALISTE",
        explain_econ_right: "Capitalisme de libre marché, déréglementation, faibles taxes, entreprise privée",
        explain_econ_left: "Intervention gouvernementale, régulation, redistribution des richesses, services publics",
        explain_soc_lib: "Valeurs progressistes, liberté personnelle, diversité, changement social",
        explain_soc_auth: "Valeurs traditionnelles, ordre social, préservation culturelle, stabilité",
        explain_diplo_global: "Coopération internationale, multilatéralisme, libre-échange, engagement mondial",
        explain_diplo_nat: "Souveraineté nationale, priorité domestique, protectionnisme, indépendance",
        explain_close: "Cliquez n'importe où à l'extérieur pour fermer",
        reset_stance: "RÉINITIALISER LA POSITION",
        reset_desc: "Refaire et Recalibrer"
    },
    settings: {
        title: "PRÉFS SYSTÈME",
        notifications: "NOTIFICATIONS PUSH",
        loc: "SERVICES LOCALISATION",
        strict: "MODE STRICT",
        reset_all_settings: "RÉINITIALISER TOUS LES PARAMÈTRES STANSE",
        reset_all_desc: "Réinitialiser toutes les préférences et reprendre le questionnaire",
        demo: "MODE DÉMO",
        delete: "Supprimer Compte & Données",
        sub_notif: "Alertes mises à jour campagnes",
        sub_loc: "Pour scan magasins locaux",
        sub_strict: "Avertir sur alignement 'Neutre'",
        sub_demo: "Inclure utilisateurs factices dans données Union",
        camera: "ACCÈS CAMÉRA",
        sub_camera: "Pour scanner les produits",
        camera_enabled: "Caméra activée",
        camera_denied: "Accès caméra refusé",
        camera_pending: "Demande d'accès...",
        language: "LANGUE",
        language_en: "English",
        language_zh: "中文",
        language_ja: "日本語",
        language_fr: "Français",
        language_es: "Español"
    },
    tour: {
        tap_anywhere: "Appuyez n'importe où pour continuer",
        skip: "Passer la visite",
        back: "RETOUR",
        next: "SUIVANT",
        finish: "TERMINER"
    },
    manifesto: {
        title: "MANIFESTE",
        subtitle: "La Philosophie de Stanse",
        p1_title: "VOTE SILENCIEUX",
        p1_body: "Nous croyons que chaque dollar dépensé est un vote. La démocratie traditionnelle a lieu tous les quelques années ; la démocratie économique a lieu tous les jours.",
        p2_title: "SOUVERAINETÉ DES DONNÉES",
        p2_body: "À l'ère du capitalisme de surveillance, nous construisons des outils qui servent l'utilisateur, pas l'annonceur. Nous ne vendons pas votre profil politique.",
        p3_title: "ACTION COLLECTIVE",
        p3_body: "Les choix individuels semblent petits, mais l'action agrégée déplace les marchés. Stanse n'est pas seulement un miroir ; c'est une lentille pour la concentration collective.",
        footer: "Ne votez pas juste. Incarnez vos valeurs."
    },
    privacy: {
        title: "ZÉRO CONNAISSANCE",
        subtitle: "ARCHITECTURE DE CONFIDENTIALITÉ",
        card_title: "NOUS NE SAVONS PAS QUI VOUS ÊTES",
        card_body: "Nous utilisons des preuves à divulgation nulle pour vérifier votre alignement sans jamais accéder à vos coordonnées politiques réelles.",
        local_title: "CALCUL LOCAL",
        local_body: "Votre \"Empreinte Politique\" est générée et stockée exclusivement sur votre appareil.",
        diff_title: "CONFIDENTIALITÉ DIFFÉRENTIELLE",
        diff_body: "Lorsque vous rejoignez une campagne, nous ajoutons du bruit aléatoire aux données, garantissant que votre contribution ne peut être isolée."
    },
    aboutUs: {
        title: "À PROPOS",
        subtitle: "Rencontrer le Fondateur",
        founder_title: "FONDATEUR",
        founder_name: "Lingxiao Xu",
        founder_bio: "Lingxiao, Stratégiste Quantitatif Senior, Vice-Président (VP) chez Goldman Sachs, détient un MBA de la Yale School of Management et est diplômé du Département IEOR de la Columbia School of Engineering. Auparavant, Lingxiao a géré des transactions au sein du Groupe de Produits Dérivés Actions chez UBS Investment Bank et a également travaillé au sein du Groupe Bank of America Merrill Lynch. Lingxiao est le Champion du Goldman Sachs Global Engineering Hackathon en 2024."
    }
  },
  [Language.ES]: {
    slogan: "No solo votes. Vive tus valores.",
    nav: { feed: "FEED", sense: "SENTIDO", stance: "POSTURA", union: "UNIÓN" },
    login: {
        title: "IDENTIFÍCATE",
        email: "CORREO ELECTRÓNICO",
        key: "CLAVE DE ACCESO",
        btn: "ESTABLECER ENLACE",
        google: "CONTINUAR CON GOOGLE",
        protocol: "Protocolo de Conocimiento Cero",
        sign_up_prompt: "¿No tienes cuenta? Regístrate",
        sign_in_prompt: "¿Ya tienes cuenta? Iniciar sesión",
        encrypted_channel: "CANAL ENCRIPTADO"
    },
    menu: {
        manifesto: "MANIFIESTO",
        privacy: "PRIVACIDAD",
        settings: "AJUSTES",
        account: "CUENTA",
        aboutUs: "SOBRE NOSOTROS",
        social: "REDES SOCIALES",
        logout: "CERRAR SESIÓN",
        subs: {
            manifesto: "Nuestra Filosofía",
            privacy: "Prueba de Conocimiento Cero",
            settings: "Preferencias",
            account: "Detalles de la Cuenta",
            aboutUs: "Conoce al Fundador",
            social: "Conectar X/Twitter"
        },
        account_email: "Correo Electrónico",
        account_reset: "Restablecer Contraseña",
        account_reset_desc: "Haga clic abajo para recibir un enlace de restablecimiento por correo",
        account_reset_sent: "¡Correo de restablecimiento enviado! Revise su bandeja de entrada.",
        account_reset_error: "Error al enviar el correo",
        premium: "Suscripción Premium",
        premium_desc: "Desbloquear funciones IA y soporte prioritario",
        subscribe_btn: "SUSCRIBIRSE",
        subscribed_btn: "SUSCRITO",
        manage_btn: "GESTIONAR SUSCRIPCIÓN",
        billing_history: "Historial de Facturación",
        payment_methods: "Métodos de Pago",
        cancel_subscription: "Cancelar Suscripción",
        confirm_charge: "CONFIRMAR CARGO",
        save_payment: "Guardar método de pago",
        promo_code: "Código Promocional",
        promo_placeholder: "Ingrese código de 8 caracteres",
        card_number: "Número de Tarjeta",
        card_name: "Nombre del Titular",
        card_expiry: "Vencimiento (MM/AA)",
        card_cvv: "CVV",
        billing_zip: "Código Postal de Facturación",
        cancel_warning: "¿Está seguro de que desea cancelar su suscripción?",
        cancel_confirm: "CONFIRMAR CANCELACIÓN",
        no_billing_history: "Aún no hay historial de facturación",
        promo_invalid: "Código promocional inválido o ya usado",
        promo_success: "¡Código promocional aplicado con éxito!",
        amount_label: "Monto",
        period_label: "Período",
        date_label: "Fecha",
        status_label: "Estado",
        manage_subscription: "GESTIONAR SUSCRIPCIÓN",
        loading_text: "CARGANDO...",
        subscription_activated: "¡Suscripción activada! Cobrado",
        promo_activated: "¡Código promocional activado con éxito!",
        subscription_failed: "Falló la suscripción",
        error_occurred: "Ocurrió un error. Por favor, inténtelo de nuevo.",
        subscription_cancelled: "Suscripción cancelada con éxito",
        cancellation_failed: "Falló la cancelación",
        active_subscription_note: "Ya tiene una suscripción activa. Puede actualizar su método de pago a continuación.",
        promo_first_time_note: "Nota: Los códigos promocionales solo se pueden usar al suscribirse por primera vez.",
        cancel_subscription_question: "¿Está seguro de que desea cancelar su suscripción?",
        trial_end_message: "Su prueba gratuita terminará en la fecha a continuación. No se aplicarán cargos.",
        promo_end_message: "Su período promocional terminará en la fecha a continuación. No se aplicarán cargos.",
        billing_end_message: "Sus funciones premium permanecerán activas hasta el final de su período de facturación actual.",
        trial_ends: "Fin de prueba",
        promo_expires: "Vencimiento de promoción",
        current_period_ends: "Fin del período actual",
        resubscribe_note: "Después de la cancelación, puede volver a suscribirse en cualquier momento.",
        payment_used: "Pago",
        promo_code_label: "Código Promo",
        status_subscribed: "SUSCRITO",
        status_trial_ended: "PRUEBA TERMINADA",
        status_promo: "PROMO",
        status_renewed: "RENOVADO",
        status_cancelled: "CANCELADO",
        promo_label: "(PROMO)",
        promo_only_new: "(Solo para nuevas suscripciones)",
        promo_not_available: "NO DISPONIBLE",
        promo_enter_code: "INGRESAR CÓDIGO",
        promo_can_only_first: "Los códigos promocionales solo se pueden usar al suscribirse por primera vez",
        promo_using_optional: "Usando código promo - info de tarjeta opcional",
        promo_leave_blank: "Dejar en blanco para pagar con tarjeta",
        card_info: "Información de Tarjeta",
        card_info_optional: "Información de Tarjeta (Opcional)",
        invalid_card: "Número de tarjeta inválido",
        invalid_expiry: "Fecha inválida o vencida",
        cvv_must_be: "CVV debe ser",
        cvv_digits: "dígitos",
        amex_4_digits: "(4 dígitos)",
        activate_promo: "ACTIVAR CON CÓDIGO PROMO",
        payment_secure: "El pago está encriptado y es seguro",
        alert_enter_name: "Por favor ingrese el nombre del titular",
        alert_valid_card: "Por favor ingrese un número de tarjeta válido",
        alert_valid_expiry: "Por favor ingrese una fecha de vencimiento válida",
        alert_valid_cvv: "Por favor ingrese un CVV válido",
        alert_billing_zip: "Por favor ingrese el código postal de facturación",
        alert_unsupported_card: "Tipo de tarjeta no soportado",
        period_to: "a"
    },
    sense: {
        title: "SENTIDO",
        subtitle: "Procesamiento de Señales • Decodificación",
        searchLabel: "BUSCAR EMPRESA, ENTIDAD O INDIVIDUO",
        placeholder: "Ej. INDITEX, PEMEX...",
        run: "ESCANEAR",
        scan_hint: "Escribe para buscar o deja vacío para escanear",
        loading: "COMPILANDO DOSSIER...",
        loading_image: "Buscando dossier para imagen identificada",
        report: "INFORME DE INTELIGENCIA",
        summary: "Resumen Ejecutivo",
        friction: "Puntos de Fricción",
        resonance: "Puntos de Resonancia",
        socialWire: "CABLE SOCIAL (X)",
        source: "Fuentes",
        btn_union: "Ver Unión",
        btn_context: "Ver Contexto",
        btn_recal: "Recalibrar Postura",
        alternatives: "Considerar en su lugar:",
        camera_title: "ESCANEO PRODUCTO",
        camera_subtitle: "Apunte la cámara al producto",
        camera_capture: "CAPTURAR",
        camera_retake: "REPETIR",
        camera_confirm: "ANALIZAR",
        camera_close: "CERRAR",
        camera_analyzing: "IDENTIFICANDO MARCA...",
        camera_no_brand: "NO SE DETECTÓ MARCA",
        camera_no_brand_desc: "No se pudo identificar el fabricante. Intente capturar una imagen más clara del logotipo.",
        camera_low_confidence: "BAJA CONFIANZA",
        camera_low_confidence_desc: "Identificación de marca incierta. Usando mejor coincidencia.",
        camera_error: "ERROR DE CÁMARA",
        camera_permission: "Se requiere acceso a la cámara"
    },
    union: {
        title: "LA UNIÓN",
        subtitle: "Acción Colectiva • Poder Descentralizado",
        network: "Red",
        your_did: "Tu DID",
        live: "EN VIVO",
        active_allies: "Aliados Activos",
        active_desc: "Recuento en tiempo real de usuarios alineando su consumo.",
        active_fronts: "FRENTES ACTIVOS",
        view_all: "VER TODOS",
        target: "OBJETIVO",
        joined: "UNIDOS",
        goal: "META",
        your_impact: "TU IMPACTO",
        ledger: "Libro Mayor Personal",
        camp_stat: "Campañas",
        streak_stat: "Racha",
        redirect_stat: "Redirigido",
        amplified: "AMPLIFICADO POR LA UNIÓN",
        union_strength: "Fuerza Total Unión",
        capital_divested: "Capital Desinvertido",
        divested_desc: "Ingresos estimados negados a entidades en conflicto."
    },
    duel: {
        title: "ARENA DE DUELO",
        subtitle: "Desafío de Habilidades Cara a Cara",
        lobby_title: "LOBBY DE DUELO",
        arena_title: "ARENA DE DUELO",
        enter_duel: "ENTRAR AL DUELO",
        how_it_works: "CÓMO FUNCIONA",
        compliance_title: "Competencia Basada en Habilidades",
        compliance_desc: "Tarifa de entrada para acceso al juego. Retiros permitidos.",
        persona: "Persona",
        balance: "Saldo",
        entry_fee: "Tarifa de Entrada",
        fee: "tarifa",
        safety_belt: "Cinturón de Seguridad",
        safety_belt_desc: "Si pierdes, solo se deduce la mitad de la tarifa de entrada",
        find_opponent: "Buscar Oponente",
        scanning: "Escaneando Red...",
        persona_mismatch: "Buscando Valores Opuestos",
        match_found: "Oponente Encontrado",
        you: "TÚ",
        opponent: "OPONENTE",
        syncing: "Sincronizando Estado del Juego...",
        ping_mismatch: "Desajuste de conexión. Reemparejando...",
        matchmaking_failed: "Emparejamiento fallido. Inténtalo de nuevo.",
        too_slow: "¡MUY LENTO!",
        opponent_first: "OPONENTE RESPONDIÓ PRIMERO",
        sec: "Seg",
        them: "Ellos",
        victory: "VICTORIA",
        defeat: "DERROTA",
        draw: "EMPATE",
        net_result: "Resultado Neto",
        safety_saved: "Cinturón Ahorró",
        rematch: "Revancha",
        back_to_lobby: "Volver al Lobby",
        victory_reward: "Recompensa de Victoria",
        funds_deducted: "Fondos Deducidos",
        draw_refunded: "Empate - Reembolsado",
        entry_card_title: "ARENA DE DUELO",
        entry_card_subtitle: "Desafío basado en habilidades",
        entry_card_live: "EN VIVO",
        entry_card_matched: "Emparejado por postura",
        entry_card_credits: "Solo créditos",
        duel_mode: "MODO DUELO",
        pvp_arena: "ARENA PVP",
        preview: "Vista previa",
        duel_description: "Trivia de imágenes basado en habilidades. Desafía a personas opuestas. Gana recompensas.",
        fast: "RÁPIDO",
        global: "GLOBAL",
        safe: "SEGURO",
        enter_arena: "ENTRAR A LA ARENA",
        duration: "Duración",
        searching: "BUSCANDO",
        finding_opponent: "Buscando un oponente con opiniones opuestas...",
        match_result: "Resultado del Partido",
        result: "RESULTADO",
        notice: "AVISO",
        low: "Bajo",
        high: "Alto",
        wallet_title: "CARTERA",
        current_balance: "Saldo Actual",
        deposit: "Depositar",
        withdraw: "Retirar",
        select_amount: "Seleccionar Cantidad",
        confirm_deposit: "Confirmar Depósito",
        confirm_withdraw: "Confirmar Retiro",
        payment_note: "Simula una pasarela de pago externa",
        insufficient_balance: "Saldo insuficiente",
        safety_belt_active: "Cinturón de Seguridad",
        time_up: "¡TIEMPO AGOTADO!",
        calculating: "Calculando resultados..."
    },
    feed: {
        market: "Alineación Mercado Valores",
        market_title: "EL MERCADO",
        market_subtitle: "SEGUIMIENTO DE VALORES EN TIEMPO REAL",
        aligned_with: "Alineado con",
        curated_for: "Seleccionado para",
        company_ranking: "Clasificación de Empresas por Valores",
        support_companies: "APOYAR",
        support_companies_tooltip: "Acciones Más Alineadas · Comprar para Apoyar",
        oppose_companies: "OPONERSE",
        oppose_companies_tooltip: "Acciones Más Opuestas · Evitar o Vender",
        loading_rankings: "ANALIZANDO EMPRESAS...",
        onboarding_required_market: "Complete la incorporación para ver acciones alineadas",
        onboarding_required_rankings: "Complete la incorporación para ver empresas alineadas",
        onboarding_required_news: "Complete su calibración de postura para obtener noticias personalizadas",
        title: "EL FEED",
        subtitle: "FLUJO DE INTELIGENCIA GLOBAL",
        lens: "LENTE PRISMA",
        close_lens: "CERRAR LENTE",
        loading_lens: "REFRACTANDO PERSPECTIVAS...",
        support: "APOYO",
        neutral: "NEUTRO",
        oppose: "CONTRA",
        index_return: "Rendimiento del Día (Long/Short)",
        index_return_tooltip: "Long Top 5 Alineadas · Short Bottom 5 Opuestas · Peso Igual",
        updated: "Actualizado",
        portfolio_index: "Índice Valores Políticos",
        portfolio_index_tooltip: "Selección via ESG · Sentimiento Noticias · Lobbying · Donaciones Ejecutivos según ejes Económico · Social · Diplomático",
        performance_tooltip: "Estrategia Long/Short Acciones: Comprar acciones alineadas con tus valores, vender en corto las opuestas. Rendimiento del portafolio = promedio de ganancias long + ganancias short.",
        persona_tooltip: "Tu persona política se determina por tus respuestas al cuestionario. El ranking de empresas se basa en: puntuaciones ESG, donaciones políticas FEC, declaraciones públicas de ejecutivos y análisis de sentimiento de noticias.",
        market_signal: "SEÑAL DE MERCADO",
        representative_positions: "POSICIONES REPRESENTATIVAS",
        why_today: "ANÁLISIS DEL DÍA",
        long_aligned: "LONG (Alineado)",
        short_opposed: "SHORT (Opuesto)",
        economic_axis: "Eje Económico",
        social_axis: "Eje Social",
        diplomatic_axis: "Eje Diplomático",
        left: "Izquierda",
        right: "Derecha",
        progressive: "Progresista",
        conservative: "Conservador",
        global: "Global",
        national: "Nacional",
        analyzing_market: "Analizando movimientos del mercado...",
        analysis_placeholder: "El análisis del mercado aparecerá aquí",
        outperforming: "EN ALZA",
        underperforming: "EN BAJA",
        today_long_short: "hoy (Long / Short)"
    },
    fingerprint: {
        title: "TU POSTURA",
        subtitle: "HUELLA POLÍTICA DINÁMICA",
        computing: "COMPUTANDO",
        identified: "PERSONA IDENTIFICADA",
        loading: "TRIANGULANDO...",
        analyzing: "ANALIZANDO COMPLEJIDAD...",
        econ: "Económico",
        soc: "Social",
        diplo: "Diplomático",
        left: "IZQ",
        right: "DER",
        auth: "AUT",
        lib: "LIB",
        nat: "NAC",
        global: "GLOBAL",
        axis_econ: "Eje Económico",
        axis_soc: "Eje Social",
        axis_diplo: "Eje Diplomático",
        label_right: "DERECHA",
        label_left: "IZQUIERDA",
        label_liberal: "LIBERAL",
        label_conservative: "CONSERVADOR",
        label_globalist: "GLOBALISTA",
        label_nationalist: "NACIONALISTA",
        explain_econ_right: "Capitalismo de libre mercado, desregulación, impuestos bajos, empresa privada",
        explain_econ_left: "Intervención gubernamental, regulación, redistribución de riqueza, servicios públicos",
        explain_soc_lib: "Valores progresistas, libertad personal, diversidad, cambio social",
        explain_soc_auth: "Valores tradicionales, orden social, preservación cultural, estabilidad",
        explain_diplo_global: "Cooperación internacional, multilateralismo, libre comercio, compromiso global",
        explain_diplo_nat: "Soberanía nacional, prioridad doméstica, proteccionismo, independencia",
        explain_close: "Haz clic en cualquier lugar fuera para cerrar",
        reset_stance: "RESTABLECER POSTURA",
        reset_desc: "Repetir y Recalibrar"
    },
    settings: {
        title: "PREFS SISTEMA",
        notifications: "NOTIFICACIONES PUSH",
        loc: "SERVICIOS UBICACIÓN",
        strict: "MODO ESTRICTO",
        reset_all_settings: "RESTABLECER TODA LA CONFIGURACIÓN DE STANSE",
        reset_all_desc: "Restablecer todas las preferencias y volver a realizar el cuestionario",
        demo: "MODO DEMO",
        delete: "Borrar Cuenta y Datos",
        sub_notif: "Alertas actualizaciones campañas",
        sub_loc: "Para escaneo tiendas locales",
        sub_strict: "Advertir en alineación 'Neutra'",
        sub_demo: "Incluir usuarios ficticios en datos de Unión",
        camera: "ACCESO A CÁMARA",
        sub_camera: "Para escaneo de productos",
        camera_enabled: "Cámara habilitada",
        camera_denied: "Acceso a cámara denegado",
        camera_pending: "Solicitando acceso...",
        language: "IDIOMA",
        language_en: "English",
        language_zh: "中文",
        language_ja: "日本語",
        language_fr: "Français",
        language_es: "Español"
    },
    tour: {
        tap_anywhere: "Toque en cualquier lugar para continuar",
        skip: "Saltar recorrido",
        back: "ATRÁS",
        next: "SIGUIENTE",
        finish: "FINALIZAR"
    },
    manifesto: {
        title: "MANIFIESTO",
        subtitle: "La Filosofía de Stanse",
        p1_title: "VOTO SILENCIOSO",
        p1_body: "Creemos que cada dólar gastado es un voto. La democracia tradicional ocurre cada pocos años; la democracia econ��mica ocurre todos los días. Tu billetera es tu urna.",
        p2_title: "SOBERANÍA DE DATOS",
        p2_body: "En la era del capitalismo de vigilancia, construimos herramientas que sirven al usuario, no al anunciante. Calculamos tus valores localmente. No vendemos tu perfil político.",
        p3_title: "ACCIÓN COLECTIVA",
        p3_body: "Las elecciones individuales parecen pequeñas, pero la acción agregada mueve los mercados. Stanse no es solo un espejo para la autorreflexión; es una lente para el enfoque colectivo.",
        footer: "No solo votes. Vive tus valores."
    },
    privacy: {
        title: "CONOCIMIENTO CERO",
        subtitle: "ARQUITECTURA DE PRIVACIDAD",
        card_title: "NO SABEMOS QUIÉN ERES",
        card_body: "Utilizamos Pruebas de Conocimiento Cero para verificar tu alineación con campañas sin acceder nunca a tus coordenadas políticas reales o historial de transacciones.",
        local_title: "COMPUTACIÓN LOCAL",
        local_body: "Tu \"Huella Política\" se genera y almacena exclusivamente en tu dispositivo.",
        diff_title: "PRIVACIDAD DIFERENCIAL",
        diff_body: "Cuando te unes a una campaña de la Unión, añadimos ruido aleatorio a los datos, asegurando que tu contribución individual no pueda ser aislada."
    },
    aboutUs: {
        title: "SOBRE NOSOTROS",
        subtitle: "Conoce al Fundador",
        founder_title: "FUNDADOR",
        founder_name: "Lingxiao Xu",
        founder_bio: "Lingxiao, Estratega Cuantitativo Senior, Vicepresidente (VP) en Goldman Sachs, posee un MBA de la Escuela de Administración de Yale y se graduó del Departamento de IEOR de la Escuela de Ingeniería de Columbia. Anteriormente, Lingxiao gestionó operaciones en el Grupo de Derivados de Acciones Estructuradas de UBS Investment Bank y también ha trabajado en Bank of America Merrill Lynch Group. Lingxiao es el Campeón del Goldman Sachs Global Engineering Hackathon en 2024."
    }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (section: keyof typeof TRANSLATIONS[Language.EN], key?: string) => any;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: Language.EN,
  setLanguage: () => {},
  t: () => ""
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(Language.EN);

  const t = (section: string, key?: string): string => {
    const translations = TRANSLATIONS[language] as Record<string, Record<string, string>>;
    const sectionData = translations[section];
    if (!sectionData) return "MISSING_SECTION";
    if (!key) return typeof sectionData === 'string' ? sectionData : "MISSING_KEY";
    return sectionData[key] || "MISSING_KEY";
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
